### ISSUE TITLE
Error count token when using 16k model

### ISSUE THREAD

**Issue by NextAlone** [xiaoxx970/chatgpt-in-terminal#57]
```
Hi, welcome to chat with GPT. Type `/help` to display available commands.
Traceback (most recent call last):
  File "/Users/xxx/.local/bin/chat", line 7, in <module>
    main()
  File "/Users/xxx/Repos/chatgpt-in-terminal/gpt_term/main.py", line 1125, in main
    chat_gpt = ChatGPT(api_key, api_timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Repos/chatgpt-in-terminal/gpt_term/main.py", line 117, in __init__
    self.current_tokens = count_token(self.messages)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Repos/chatgpt-in-terminal/gpt_term/main.py", line 616, in count_token
    encoding = tiktoken.get_encoding("cl100k_base")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Repos/chatgpt-in-terminal/.venv/lib/python3.11/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "/Users/xxx/Repos/chatgpt-in-terminal/.venv/lib/python3.11/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Repos/chatgpt-in-terminal/.venv/lib/python3.11/site-packages/tiktoken/load.py", line 117, in load_tiktoken_bpe
    return {
           ^
  File "/Users/xxx/Repos/chatgpt-in-terminal/.venv/lib/python3.11/site-packages/tiktoken/load.py", line 119, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
        ^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by NextAlone** [comment]
Solved by `https://github.com/openai/tiktoken/issues/114`

**Comment by Ace-Radom** [comment]
I cannot reproduce this error, can you maybe give a brief introduction how this error occured? (e.g. what did you do, your config settings, logs, etc)
btw, my local tiktoken module version is also 0.3.3 but the error reported in this issue and [tiktoken#114](https://github.com/openai/tiktoken/issues/114) didn't occur (using gpt-3.5-turbo-16k model), but it's also possible that this error doesn't appear all the times, idk. The easiest way to solve this problem is to set a min-version in [requirements.txt](https://github.com/xiaoxx970/chatgpt-in-terminal/blob/main/requirements.txt), but idk if it's really necessary.

**Comment by NextAlone** [comment]
```
> pip list
Package            Version
------------------ ---------
aiohttp            3.8.4
aiosignal          1.3.1
async-timeout      4.0.2
attrs              22.2.0
certifi            2022.12.7
charset-normalizer 3.1.0
frozenlist         1.3.3
idna               3.4
markdown-it-py     2.2.0
mdurl              0.1.2
multidict          6.0.4
openai             0.27.2
packaging          23.1
pip                22.3.1
prompt-toolkit     3.0.38
Pygments           2.14.0
pyperclip          1.8.2
python-dotenv      1.0.0
python-i18n        0.3.9
PyYAML             6.0
regex              2023.3.23
requests           2.31.0
rich               13.4.2
setuptools         65.6.3
sseclient-py       1.7.2
tiktoken           0.4.0
tqdm               4.65.0
urllib3            1.26.15
wcwidth            0.2.6
yarl               1.8.2
```

Reproduced, with `TIKTOKEN_CACHE_DIR` not set, and no matter which model.

**Comment by NextAlone** [comment]
Though, reproduced with 0.3.3.
![image](https://github.com/xiaoxx970/chatgpt-in-terminal/assets/12210746/fe59372e-c846-4e68-a7be-8374608e40e5)
