### ISSUE TITLE
pip 安装后直接运行gpt-term是运行的哪个py程序？

### ISSUE THREAD

**Issue by MichaelC001** [xiaoxx970/chatgpt-in-terminal#59]
pip show gpt-term 显示gpt-term 文件夹如下
/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/gpt_term
这个文件夹下面没有chat.py这个文件
我进入这个文件夹 运行python main.py 报错

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/gpt_term/main.py", line 23, in <module>
    import tiktoken
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/tiktoken/__init__.py", line 1, in <module>
    from .core import Encoding as Encoding
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/tiktoken/core.py", line 7, in <module>
    import regex
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/regex/regex.py", line 424, in <module>
    from locale import getpreferredencoding as _getpreferredencoding
ImportError: cannot import name 'getpreferredencoding' from 'locale' (/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/gpt_term/locale.py)

=======================
但是直接用pip安装后，运行gpt-term 没问题

**Comment by xiaoxx970** [comment]
确实不应该直接到site-packages文件夹直接运行脚本的，那样会导致相对目录倒入包错误。
你可以通过pip包运行gpt-term：
```sh
pip -m gpt_term
```
或者直接运行gpt-term
```sh
gpt-term
```
如果想要直接运行chat.py文件，可以先把这个 repo 克隆到本地后运行此目录下的chat.py
```sh
git clone https://github.com/xiaoxx970/chatgpt-in-terminal
cd chatgpt-in-terminal
python3 chat.py
```
